### ISSUE TITLE
additional metadata

### ISSUE THREAD

**Issue by lkuiucsb** [BLE-LTER/MetaEgress#19]
If a data package has only "otherEntity", there won't be "additional metadata". The current Rcode would generate an EML node with "NULL" in the additional metadata. The code should be able to remove the node when there is no additional metadata.

**Comment by atn38** [comment]
Currently, the only condition under which we generate additionalMetadata is if there are custom units. There can only be custom units if there are attributes, so there should be none if you only have otherEntity-types. 

Are you finding that currently additionalMetadata is still generated with only otherEntity's?

**Comment by lkuiucsb** [comment]
There is no additional metadata when there is only "otherEntity". However, the eml shows as <additionalMetadata> NULL </additionalMetadata>. This will not pass the EML validation.

**Comment by atn38** [comment]
How are you validating your EML? I use `EML::eml_validate` and this minimal
example with additionalMetadata = NULL passes with no errors.

```
library(EML)

person <-
  list(individualName = list(givenName = "Blizzard", surName = "Frosty"))

my_eml <- list(
  packageId = "id",
  system = "system",
  dataset = list(
    title = "A Mimimal Valid EML Dataset",
    creator = person,
    contact = person
  ),
  additionalMetadata = NULL
)

eml_validate(my_eml)
```

**Comment by atn38** [comment]
this should be handled now. closing.
