### ISSUE TITLE
make call to PASTA/EDI API to generate provenance from packageId

### ISSUE THREAD

**Issue by atn38** [BLE-LTER/MetaEgress#36]

**Comment by gastil** [comment]
example:
GET : https://pasta.lternet.edu/package/provenance/eml/{scope}/{identifier}/{revision}

Here is the pasta api doc page for provenanceGenerator: https://pastaplus-core.readthedocs.io/en/latest/doc_tree/pasta_api/data_package_manager_api.html#provenance

It says " an XML document containing a single methods element in the request message body." but fortunately it actually returns a methodStep tree.

**Comment by atn38** [comment]
closing, functionality already folded in, seems to work pretty ok
