### ISSUE TITLE
apostrophe messes up row count when computing number of records

### ISSUE THREAD

**Issue by twhiteaker** [BLE-LTER/MetaEgress#79]
An apostrophe in a CSV cell value in a data table, e.g., "I've had it up to here with bugs", messes up the row count when computing number of records in create_entity.  I found that it added an extra record in my case. Perhaps rewrite the function so it has a more robust row counting scheme. RStudio shows the correct number of rows in the data frame, so I know it's possible.

**Comment by Indujamohandas** [comment]
fixed in 626a8f2235d83459f5fcad1aaf05a968254358d0
